# @package _global_

defaults:
  - hm3d
  - _self_

habitat:
  dataset:
    data_path: /opt/rt_ovn/data/datasets/objectnav/hm3d/v2/{split}/{split}.json.gz
    scenes_dir: /opt/rt_ovn/data/scene_datasets
